### ISSUE TITLE
C++ simulatorized tests do not run job.py per TestSimulator instance.

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#103]
The previous test cases which were changed to use the simulator and "job.py", only run job.py once.

This may not strictly be an issue as the variance is over the dimension and interp_order, and in these cases the explicit template parameters of the Simulator class are controlled from C++.

**Comment by nicolasaunai** [comment]
close?

**Comment by Dekken** [comment]
this is sort of, but not completely assessed in https://github.com/PHAREHUB/PHARE/pull/216
