### ISSUE TITLE
possible MPI / smallest patch size issue

### ISSUE THREAD

**Issue by Dekken** [PHAREHUB/PHARE#120]
refinement_boxes": {"L0": {"B0": [(10,), (14,)]}}

 doesn't work with

    mpirun -n 2

it only starts to work when 14 is changed to 19

**Comment by nicolasaunai** [comment]
still open?

**Comment by Dekken** [comment]
it's fixed in https://github.com/PHAREHUB/PHARE/pull/106

perhaps we can fix it in isolation, the refinement_box tests on master (tests/simulator/py) should suffice

do we want to reproduce a minimal test to show that flush can be synchronous?
