### ISSUE TITLE
Test that root ghost nodes are filled properly after user initialization

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#16]
User initialization of the root level finishes with calling fillRootGhosts.
This test intends to check that electromagnetic, moments and patchGhostParticles are well filled.

**Comment by Dekken** [comment]
is this resolved by https://github.com/PHAREHUB/PHARE/pull/82 ?

**Comment by nicolasaunai** [comment]
no, there are no tests in #82

**Comment by nicolasaunai** [comment]
redundant with #93
