### ISSUE TITLE
python boundary_types not connected to C++

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#166]
hopefully wrong but it looks like ```https://github.com/PHAREHUB/PHARE/blob/master/pyphare/pyphare/pharein/__init__.py#L79```

isn't used anywhere

**Comment by nicolasaunai** [comment]
link is invalid it seems...? I get 404
this will need to be investigated when non periodic boundary conditions will be implemented

**Comment by PhilipDeegan** [comment]
updated link

**Comment by PhilipDeegan** [comment]
closed by #798
