### ISSUE TITLE
implement moveIons

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#17]
moveIons is the function that takes electromagnetic fields, ions and move the ion distribution and moments.

The implementation can be inspired from the design project : https://hephaistos.lpp.polytechnique.fr/rhodecode/GIT_REPOSITORIES/LPP/phare/tests/particledesign/files/257aad76884cbc1fe142917bd82b1b5470002752/interface/solverppc.cpp#L134

**Comment by nicolasaunai** [comment]
# Ion Mover

## Definition

IonMover is a component that takes (at least) :

- Ions
- Electromag

and can evolve the ion particle distribution and ion moments from time n to n+1.


## Assumptions & Requirements

- the caller sets the data (Ions and Electromag) on patch beforehand so data is readily usable

IonMover is needed during the advancement of the level solution by the solver.
In the predictor-predictor-corrector scheme, particles and moments are evolved twice.

Both phases move the particles and moments from t=n to t=n+1. Therefore the particle state at t=n+1 needs to be "saved" somehow. Therefore : 

- the caller may want to evolve only moments to t=n+1 and leave particles at t=n or evolve both to t=n+1

- is given a dictionary at construction to build the right pusher


## Needs

at least : 

- an interpolator, to compute moments from particles
- a pusher, to push particles from t=n to t=n+1


## Tests

Tests need a full hybrid hierarchy setup, with non-zero electromagnetic field and non-zero temperature. A uniform plasma should be used for simplicity.

- In case no particle update is required:
    - [ ] particles attributes should remain equal to what they were before calling the mover. 
    - [ ] moments should be different than before calling the mover

- in case particle update is required: 
    - [ ] particles should have moved and their velocity changed compared to before calling the mover
    - [ ] moments should be different as well

- in all cases:
    - [ ] all nodes supposed to be complete are indeed complete. This means their moment is "close" to the expected value.
    - [ ] all nodes supposed to be unused are set to NaN.

    - [ ] should work for any interpolation order
    - should work for any dimension 
    - [ ] should work for any number of populations

**Comment by Dekken** [comment]
> A uniform plasma should be used for simplicity.

does this mean there is no always "no particle update required"? if not, what is the the distinction between the two cases of requiring an update or not.

Particles leaving/entering patches, do we manage that, if so, please elaborate.

**Comment by nicolasaunai** [comment]
I'm adding that we need to make sure the fake patch we assume the data is coming from lies on the border of a level so that it has both patchGhostParticles and levelGhostParticles. Said differently we need to load these particles manually because the particleInitializer only loads domain particles (in reality ghosts are taken care by SAMRAI whether they live on level or patch ghost areas)

**Comment by nicolasaunai** [comment]
the point
```
particles should have moved and their velocity changed compared to before calling the mover
```

is not checked because it is not easy, once they have been moved, to compare the new particle array with its state before moving particles. The main reason being that some particles have left the domain, and the whole array has been changed due to the partitioning in the pusher.
