### ISSUE TITLE
OMPI issue with patch hierarchy access in datawrangler

### ISSUE THREAD

**Issue by Dekken** [PHAREHUB/PHARE#185]
```
MPI_ABORT was invoked on rank 2 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode -1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[imaccm:38724] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[imaccm:38724] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
[imaccm:38724] Set MCA parameter “orte_base_help_aggregate” to 0 to see all help / error messages
```

possibly related
```
https://github.com/open-mpi/ompi/issues/7516
```

**Comment by Dekken** [comment]
investigations suggest it's SAMRAI VariableDatabase / ResourceManager related.

**Comment by nicolasaunai** [comment]
is it possible samrai is killed before the resourcesManager destructor (which accesses the variabledatabase) it called? We got this error once already, that leads to dangling refs

**Comment by Dekken** [comment]
possible perhaps

If I recall the stacktrace suggested it was not on setup or shutdown, but during hierarchy accessing.
I'm trying to reproduce it again to get the trace but it's not happening

**Comment by Dekken** [comment]
solved by https://github.com/PHAREHUB/PHARE/pull/236
