### ISSUE TITLE
3d Splitting

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#232]
started here: 
https://github.com/Dekken/PHARE/blob/3d/src/amr/data/particles/refine/split_3d.h

See Roch's comments here:
https://github.com/PHAREHUB/PHARE/pull/154/files/5a24b9f154f5699e5d7a6e7ded8f6f31ca506802#diff-3748933c00c50a7a0a29554de725cf75

**Comment by Dekken** [comment]
TODO: https://github.com/PHAREHUB/PHARE/blob/master/pyphare/pyphare_tests/pharein/simulation_test.py#L17

re-add dim = 3

**Comment by Dekken** [comment]
3d fixMomentGhosts (WIP) https://github.com/Dekken/PHARE/blob/nanners3d/src/core/data/ions/ions.h

**Comment by PhilipDeegan** [comment]
done in #591

**Comment by PhilipDeegan** [comment]
duplicate of https://github.com/PHAREHUB/PHARE/issues/110
