### ISSUE TITLE
Meta - fanalyzer results

### ISSUE THREAD

**Issue by Dekken** [PHAREHUB/PHARE#235]
https://hephaistos.lpp.polytechnique.fr/teamcity/buildConfiguration/Phare_Phare_BuildFanalyzer/58848?buildTab=log&focusLine=2374&linesState=206

https://github.com/PHAREHUB/PHARE/blob/master/src/amr/data/field/field_geometry.h#L62

Should the "retry" branch ever happen?

**Comment by nicolasaunai** [comment]
I don't think so... what's going on could you decrypt the pb with the analysis for me plz?

**Comment by Dekken** [comment]
I think it's similar to the previous analyses when we were casting pointers and checking if they were valid.

If we just cast to & the branch seems redundant

**Comment by nicolasaunai** [comment]
well, if I remember well, previously the else branch (in copy?) was throwing anyway... in the current case it does not and just calculates the overlap differently...
But anyway, I don't see why the casts should not work...
