### ISSUE TITLE
have a mac image in the CI

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#248]
Multiple times we had discrepancies in behaviours between linux and mac. We need to have builds on mac OS.

**Comment by nicolasaunai** [comment]
closed because GH action mac image

**Comment by PhilipDeegan** [comment]
GH actions are not so realiable, so we should look into having MacOS VMs via ICDS VM cluster with TC integration https://www.jetbrains.com/help/teamcity/setting-up-teamcity-for-vmware-vsphere-and-vcenter.html

**Comment by nicolasaunai** [comment]
cirrusCI?

**Comment by PhilipDeegan** [comment]
we should try github again, it stopped working cause I think they switched to M1/ARM
we were getting issues with system libs (libquadmath) 
things might be working since then
or, there might still be an intel macos image we can use
tbc

**Comment by PhilipDeegan** [comment]
see https://github.com/PHAREHUB/PHARE/issues/732

**Comment by nicolasaunai** [comment]
This is mainly for contributors that would be on Mac.

**Comment by nicolasaunai** [comment]
#755
