### ISSUE TITLE
allow splitting from python

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#257]
splitter wrapper in cpp_simulator should allows, from python, to provide an array of particles and get an array of refined particles from them.

Linked to #93 for levelGhost particle more specifically.

**Comment by nicolasaunai** [comment]
linked to 
https://github.com/Dekken/PHARE/blob/5d74213118810db5884c56d2ae37650d2066b3d0/tests/simulator/test_simulator_pybind.cpp

**Comment by Dekken** [comment]
closed by https://github.com/PHAREHUB/PHARE/pull/258
