### ISSUE TITLE
ASAN possible memory leaks

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#276]
```
4/49 Test  #5: test-particles-data-copy-with-overlap ....***Failed    1.05 sec
5/49 Test #10: test-field-data-copy .....................***Failed    1.08 sec
6/49 Test  #9: test-field-data-coarsen ..................***Failed  

...

51% tests passed, 24 tests failed out of 49
```

https://hephaistos.lpp.polytechnique.fr/teamcity/buildConfiguration/Phare_Phare_BuildGithubPrClangAsan/61000?buildTab=log&focusLine=3&linesState=1625

**Comment by Dekken** [comment]
locally I get 

```
82% tests passed, 9 tests failed out of 49
```

**Comment by Dekken** [comment]
quite possibly all python internal leaks

**Comment by PhilipDeegan** [comment]
ASAN is run on CI but memory leak detection is disabled, still suspecting python is what is leaking
