### ISSUE TITLE
investigate fPIC slowdown

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#279]
fPIC is suggested to cause a slow down, we have it enabled, but we might not need it for static builds

https://stackoverflow.com/questions/15861759/how-much-overhead-can-the-fpic-flag-add

"From the other side dynamically linked executables use shared libraries compiled in PIC (position independend code) which is slower than "normal" one." ```http://statifier.sourceforge.net/```

**Comment by Dekken** [comment]
additionally, investigate the impact/necessity of the following:

CFLAGS="-fPIE -fstack-protector-all -D_FORTIFY_SOURCE=2" 
LDFLAGS="-Wl,-z,now -Wl,-z,relro"

**Comment by PhilipDeegan** [comment]
I think we can disable 

```
CMAKE_POSITION_INDEPENDENT_CODE
```

for most things and fPIC will still be used for the pybind libs as I think it needs it, tbc

**Comment by PhilipDeegan** [comment]
for the pybind lib I don't think we can not use it, so it's only really appropriate for `phare-exe`

https://stackoverflow.com/a/57245146

**Comment by PhilipDeegan** [comment]
ok we can't do really turn it off 

```
 src/core/libphare_core.a(mpi_utils.cpp.o): relocation R_X86_64_PC32 against symbol `ompi_mpi_comm_world' can not be used when making a shared object; recompile with -fPIC
```
