### ISSUE TITLE
add gcc 7..9 and clang 6..9 to the CI

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#28]
there should be a build conf (or several) on the CI that builds PHARE for versions of gcc from 7 to 9, and clang from 6 to 9. Use the already packaged versions of the compilers.

**Comment by nicolasaunai** [comment]
can this be closed?

**Comment by PhilipDeegan** [comment]
the build matrix is there now on TC so I suppose so
