### ISSUE TITLE
cmake - investigate IPO/LTO link failures

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#326]
fails with clang 10 on juno

**Comment by Dekken** [comment]
what is LTO:
https://gcc.gnu.org/wiki/LinkTimeOptimization
https://wiki.debian.org/LTO

**Comment by PhilipDeegan** [comment]
I think we turn this off for pybind, tbc

**Comment by nicolasaunai** [comment]
Ok I'll let you close that one when you see fit

**Comment by PhilipDeegan** [comment]
I've tried compiling with LTO on and position independent code off ( fPIC ) and everything works, so I think closed

further reading on LTO for posterity https://convolv.es/guides/lto/
