### ISSUE TITLE
Possible nullptr if coarser level has no patch

### ISSUE THREAD

**Issue by Dekken** [PHAREHUB/PHARE#331]
contrived test case where min/max patch size = domain size, with >= 2 mpi_cores 

https://github.com/PHAREHUB/PHARE/blob/bf5212d4ce7d3568d0165e720fe58b6d1281b86a/src/amr/messengers/hybrid_hybrid_messenger_strategy.h#L384

**Comment by Dekken** [comment]
```assert(*std::begin(*hierarchy->getPatchLevel(levelNumber)));``` fails

**Comment by nicolasaunai** [comment]
the patch here is used to get the times of ion resources, to know what is the "new" coarse time (after coarse push).
There may be another solution to get this time than using a patch, because using a patch assumes the current process indeed has at least one patch on the next coarser.....

**Comment by nicolasaunai** [comment]
fixed by #337
