### ISSUE TITLE
possibly cleaner solution with std::mem_fn

### ISSUE THREAD

**Issue by Dekken** [PHAREHUB/PHARE#334]
https://github.com/PHAREHUB/PHARE/blob/bdf695b6ed78e9db31b049842502acd405c89ec3/tests/diagnostic/test_diagnostics.h#L28

see: https://en.cppreference.com/w/cpp/utility/functional/mem_fn

**Comment by Dekken** [comment]
done as part of https://github.com/PHAREHUB/PHARE/pull/325

**Comment by nicolasaunai** [comment]
maybe using MaskedView works now for selecting domain nodes, or domain+1 nodes, etc.? or are more complicated filters expected?

**Comment by Dekken** [comment]
I don't expect more complicated filters, I think you said that the MaskedView wasn't sufficient. I might imagining it.
