### ISSUE TITLE
less refined levels than max_nbr_levels leads to segault

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#344]
max_nbr_levels=3 with only 1 refined level boxes specified leads to crash. max_nbr_levels less than specified in refinement boxes is checked but the inverse should also be.

**Comment by Dekken** [comment]
could we override "max_nbr_levels" if it's bigger than the highest refined_box config?

**Comment by nicolasaunai** [comment]
you mean setting the param to a value that would enable to run the simulation?
if documented that could be done maybe....

**Comment by Dekken** [comment]
if it's a purely refined_box simulation with no tagging I don't see it having any side-affects

**Comment by nicolasaunai** [comment]
linked to #377

**Comment by nicolasaunai** [comment]
can be closed now no?
