### ISSUE TITLE
test refinement boxes are valid in simulation

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#362]
check_refinement_boxes should validate that refinement boxes are within the next coarser level patch boxes... for L1 it should be whtin domain_box and for L2...N it should be within any of the previous level refinement boxes.

This should be part of that function : 

https://github.com/PHAREHUB/PHARE/blob/master/pyphare/pyphare/pharein/simulation.py#L214

and typically this : https://github.com/PHAREHUB/PHARE/blob/master/tests/simulator/refinement_boxes.py#L44
should fail as a result of the check, because 55 cells domain does not allow refinement boxes to go up to 65.

One way to do it is to make a pyphare.core.box.Box from the user box input, and use the ` in` box operator to check if a given box is "in" another (domain_box or next coarser refinement boxes)

**Comment by Dekken** [comment]
is it not possible that a refined patch could be across two adjacent coarser patches?

**Comment by rochSmets** [comment]
I think that yes, it could. But anyway, the box including this path should itself be entirely included in a box of the next coarser level. If I'm correctly understanding, that is the reason why we deal with boxes and not patches.

**Comment by Dekken** [comment]
ok, this should be handled by #377 then

**Comment by nicolasaunai** [comment]
can we close this?

**Comment by PhilipDeegan** [comment]
currently it's expected that a finer patch box is completely within a coarser box, not that it is completely above a set of coarser boxes, which would be more flexible

**Comment by PhilipDeegan** [comment]
https://github.com/PHAREHUB/PHARE/pull/409
