### ISSUE TITLE
Test Field refinement in 2D and 3D

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#363]
test/amr/data/field/refine/test_basic.hierarchy.cpp

the test "ALinearFieldRefine1DO1, conserveLinearFunction" is initializing an AMR hierarchy parametrized by the input/input_1d_ratio_xx.txt files where basically all PHARE quantity fields live. 

It initializes the root level with a linear function of the position x, and the finer levels with a refinement schedule.

The test checks that fine levels nodes, for all fields, equal the value given by the linear function at these nodes. This should be true exactly because the refinement itself is linear.

The goal of this issue is to update the test so that it runs in 2 and 3D.
Non exhaustive and rough lsit of things to consider : 

- [x] having an input txt file for a 2D and a 3D case, only for refinement ratio 2 is enough
- [x] modifying the tagging TagStrategy to intialize root level with a 2D and 3D linear function. These functions should use x AND y in 2D, and x and y and z in 3D so that each node value is unique.
 - [x] considering having a linear function that is different for each quantity is a plus.

**Comment by rochSmets** [comment]
I'm starting to work on this one...

**Comment by rochSmets** [comment]
ok
