### ISSUE TITLE
Assess BergerRigotsos VS TileClustering

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#473]
- may need to add that from python input as user param
- needs to assess modifications to performances (probably PHARE2D)

**Comment by PhilipDeegan** [comment]
examples ![image](https://user-images.githubusercontent.com/30491/180045042-368d46db-f239-4247-987c-24c51d91699b.png)

**Comment by nicolasaunai** [comment]
Not much to add for now. Tile Clustering seems to produce no artifact, Berger Rigoutsos maybe a bit. tag_buffer and smallest_patch_size help not to have very localized and small patches (prone to complex coarse to fine boundaries and maybe artifacts). Berger Rigoutsos produces more patches and therefore it's easier for Tile Clustering to lead to low number of patches for small simulations and challenge load balancing.
