### ISSUE TITLE
random bug in maxwellian particle initializer

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#479]
It seems there are sometimes one (at least?) particle initialized outside the domain with the maxwellian initializer as is.
We should make a test that runs this module multiple times to see it systematically.  Usually this kind of bug happens when a particle is by chance placed "exactly" on the right border, i.e. iCell is last cell and delta==1. We however draw the delta from a uniform distribution bounded by 1-epsilon. My current idea is that this epsilon (using numerical limits double) is too small for some reason I don't understand.

**Comment by PhilipDeegan** [comment]
can be reproduced sporadically via tests/core/data/maxwellian_particle_initializer/test_maxwellian_particle_initializer.cpp

```
TEST_F(AMaxwellianParticleInitializer1D, loadsParticlesInTheDomain)
...
    EXPECT_TRUE(pos[0] > 0. && pos[0] < endDomain);
```
fails

**Comment by PhilipDeegan** [comment]
haven't seen this in a while

**Comment by PhilipDeegan** [comment]
don't recall seeing this again

**Comment by nicolasaunai** [comment]
good reason to close
