### ISSUE TITLE
commit sha in all diag files top attribute

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#489]
For reproductibility it would be nice to have the commit id as an attribute and any diagnostic file.

**Comment by PhilipDeegan** [comment]
will add a means to add arbitrary key/values from python to h5 files, so git sha can be done via python

both phare-exe and pyphare use python diagnostics, so both current execution methods are handled

**Comment by nicolasaunai** [comment]
we should also consider adding references to the version of dependencies... maybe both those as subproject/submodules and those found in the system
