### ISSUE TITLE
write diagnostics to disk

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#5]
PHARE needs to output data to disk.
- [x] Write particles for each population
- [x] Write density for ions and populations
- [x] Write bulk velocity and flux for ions and populations
- [x] Write Electromagnetic fields
- [x] Datasets are written per patch per level
- [x] both particle and field ghost nodes are written
- [x] All levels specified by the user need to written at sync points.
- [ ] User can specify the dump times
- [x] Diags are written in HDF5 using HighFive
- [x] Dual/Primal value in each direction should be given for each field written or the Diagnostic file should specify the layout type (e.g. Yee) and python post-proc routines know what is where.
- [x] write time of the dump as an HDF5 group (first after root)
- [x] Diagnostics are specified by blocks in job.py and passed to pyphare in Simulation/Diagnostics/
- [x] User can ask for either E or B or  both in Electromag Diag
- [x] User can ask for specific Fields or VecFields of total ions or specific Populations in FluidDiagnostics

**Comment by Dekken** [comment]
points of discussion with @nicolasaunai 

- optionally dump ghost nodes when compiled with debug flag
- optionally dump particles at user determined intervals
- think how to structure hdf5 hierarchy with regard to sub-timesteps
   - is this optional/configurable?
   - do we just provide data from synchronization points?

@nicolasaunai please review and add to if you see fit.

**Comment by Dekken** [comment]
- Which indexes should patches contain, local/global, and what methodology surrounds them

**Comment by nicolasaunai** [comment]
User inputs (data provider) gives the diagnostics module which diagnostics (E ? B ? both ? ion moments ?  particles ? which population ?) are to be written and when.

We should start writing all user chosen diags in the h5 hierarchy at times based on the coarsest level time steps. Accessing refined level substeps is going to be difficult anyway.

We can provide the user with two modes: mode 'light' writes only the coarsest level (which has felt the refined solutions nonetheless), the mode 'full' writes the full hierarchy (i.e. all levels and all patches). 

Writing ghost nodes (for fields and particles) can remain a compile time option.

**Comment by Dekken** [comment]
I think https://github.com/PHAREHUB/PHARE/pull/141 will close this one
