### ISSUE TITLE
gridlayout::AMRToLocal signedness

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#558]
should probably only accept signed ints. and should probably only return unsigned ints

**Comment by PhilipDeegan** [comment]
this is done in #654

**Comment by PhilipDeegan** [comment]
I have this on my SOA/GPGPU branch
but it's not hard to redo

**Comment by nicolasaunai** [comment]
ok no worries I was not sure it was there since the PR was closed.
