### ISSUE TITLE
Problem with "make"

### ISSUE THREAD

**Issue by Afftar123** [PHAREHUB/PHARE#566]
Hello! When I tried to make phare I get this error (cmake .. runs without problem)

In file included from /home/afftar/Documents/PHARE-master/src/initializer/data_provider.cpp:2:
/home/afftar/Documents/PHARE-master/src/initializer/data_provider.h:10:10: fatal error: cppdict/include/dict.hpp: Нет такого файла или каталога
   10 | #include "cppdict/include/dict.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/initializer/CMakeFiles/phare_initializer.dir/build.make:82: src/initializer/CMakeFiles/phare_initializer.dir/data_provider.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:7724: src/initializer/CMakeFiles/phare_initializer.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…
[ 20%] Built target SAMRAI_hier
make: *** [Makefile:160: all] Ошибка 2

Can you help me with this? Thanks in advance

**Comment by PhilipDeegan** [comment]
can you try the following:

```
git submodule update --init
```

**Comment by PhilipDeegan** [comment]
did you happen to download PHARE as a zip? That will not work so simply.

I suggest you clone again with 

```
git clone https://github.com/PHAREHUB/PHARE --recursive
```

**Comment by Afftar123** [comment]
Yes, you're right. Now it works! Thank you.
And, one more question, is there are more or less "detailed" documentation for PHARE?

**Comment by PhilipDeegan** [comment]
for the moment I can only suggest you look at the different functional tests we have in the directory 
https://github.com/PHAREHUB/PHARE/blob/master/tests/functional

for instance
https://github.com/PHAREHUB/PHARE/blob/master/tests/functional/alfven_wave/alfven_wave1d.py

the steps to execute one of these would be 

```
git clone https://github.com/PHAREHUB/PHARE --recursive phare
cd phare && mkdir build && cd build && cmake .. && make -j && cd ..
export PYTHONPATH=$PWD:$PWD/build:$PWD/pyphare
python3 tests/functional/alfven_wave/alfven_wave1d.py
```

if you're missing some python packages you might try

```
python3 -m pip install pip --upgrade
python3 -m pip install -r requirements.txt --upgrade
```

**Comment by Afftar123** [comment]
Ok! Thanks a lot

**Comment by nicolasaunai** [comment]
> Yes, you're right. Now it works! Thank you.
> And, one more question, is there are more or less "detailed" documentation for PHARE?

please not the code is still in a development phase and has not yet been used for science production runs ;-)
