### ISSUE TITLE
SAMRAI patch hierarchy includes patches that are too small

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#577]
![image](https://user-images.githubusercontent.com/30491/123461443-6c89d280-d5e9-11eb-8d52-eea46e16278a.png)

domain size 30 had a patch decomposition with size 3 patches, creating race conditions on shared border value of close but not adjacent patches

**Comment by PhilipDeegan** [comment]
see https://github.com/LLNL/SAMRAI/issues/171

**Comment by PhilipDeegan** [comment]
we could/should validate all patches are greater than a minimum after initilization

**Comment by nicolasaunai** [comment]
I don't think we have race conditions now with the shared node fillPattern trick, and there is probably not much we can do about SAMRAI giving us patches smaller than wished. As long as we don't see issues with them I think it's ok. Might be an issue for perf if too many of those, but TBD. In the mean time, closing.
