### ISSUE TITLE
get python stack trace from pybind?

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#66]
It would be convenient to get the python stack trace from pybind, when phare crashes due to errors in init.py.

**Comment by Dekken** [comment]
there is a hint already 

```
test
unknown file: Failure
C++ exception with description "NameError: name 'simulation' is not defined

At:
  init.py(7): <module>
" thrown in the test body.
Segmentation fault
```

**Comment by nicolasaunai** [comment]
yes... I wrote the issue before I saw that. not sure more is needed

**Comment by Dekken** [comment]
I had a look for something more but I couldn't find anything, wrapping "eval_file" in a try/catch doesn't seem to work either

**Comment by nicolasaunai** [comment]
let's close then?
