### ISSUE TITLE
simulator.py PHARE_LOG make .log if env var is set

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#668]
and move these checks out of the simulator to the simulation so phare-exe also makes use of it

**Comment by nicolasaunai** [comment]
Also move the mechanism to the Simulation rather than the simulator

**Comment by PhilipDeegan** [comment]
it's not so simple as we check for mpi_rank 0 and it's in the simulator.py that we initialize MPI
