### ISSUE TITLE
restarts / timesteps / finaltime

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#670]
Currently in #649, there might be some confusion remaining around how many timesteps a restarted simulation will run, given the simulation parameters.

If a simulation ends after 10000 timesteps, and saves the restart file there.
If this simulation is restarted, without increasing the timestep number, it will not advance, as it is already "finished".

**Comment by nicolasaunai** [comment]
I think that's the user's responsibility to check that the simulation final_time is updated if one wants to restart at a checkpoint done at the previous job's final_time.
I'm therefore closing this issue. If needed one could add a check in python that restart_time, if provided, should be greater or equal to final_time+dt
