### ISSUE TITLE
`SolverMHD` never used

### ISSUE THREAD

**Issue by v01dXYZ** [PHAREHUB/PHARE#728]
## Summary
 
* observation: `SolverMHD` doesn't seem to be used by any other parts of the code base.
* version: b1a9ec3804058865f16b6602bf5ba5d7633de212

## Details

Grepping for  `SolverMHD` or `"MHDSolver"` shows the code for this solver is possibly not used (cf  [solver_mhd.hpp](https://github.com/PHAREHUB/PHARE/blob/b1a9ec3804058865f16b6602bf5ba5d7633de212/src/amr/solvers/solver_mhd.hpp)).
The code in `test_multiphysics_integrator` doesn't cover this solver although we can found its name:

https://github.com/PHAREHUB/PHARE/blob/b1a9ec3804058865f16b6602bf5ba5d7633de212/tests/amr/multiphysics_integrator/test_multiphysics_integrator.cpp#L68-L72

but `isInMHDRange` always returns `false`:

https://github.com/PHAREHUB/PHARE/blob/b1a9ec3804058865f16b6602bf5ba5d7633de212/tests/amr/multiphysics_integrator/test_multiphysics_integrator.cpp#L10-L20

**Comment by PhilipDeegan** [comment]
MHD is planned, but not yet implemented.

**Comment by v01dXYZ** [comment]
Thanks for the answer. Good to know.
