### ISSUE TITLE
Fedora 39 failing on TC

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#770]
gitstats is not yet available for FC39

https://src.fedoraproject.org/rpms/gitstats

check periodically 

reason: we try to install gitstats during the dockerfile building @ https://github.com/PHARCHIVE/phare-teamcity-agent

**Comment by PhilipDeegan** [comment]
gitstats appears to no longer be maintained so we might need to drop it

**Comment by nicolasaunai** [comment]
yeah, it's not like we were looking at it everyday...
it was nice though but I don't see many alternatives

**Comment by PhilipDeegan** [comment]
there's no real rush on this as I would typically not use the latest FC release while it matures, but it is good to have in case we sporadically want to test something

todo: remove gitstats from dockerfile https://github.com/PHARCHIVE/phare-teamcity-agent/blob/master/Dockerfile#L14
