### ISSUE TITLE
delete the schedules associated to a level removed from the hierarchy by samrai

### ISSUE THREAD

**Issue by nicolasaunai** [PHAREHUB/PHARE#87]
We store our schedules in the messengers. Whenever SAMRAI removes a level, the associated schedules should be deleted as well.

**Comment by Dekken** [comment]
probably by implementing a version of "processLevelBeforeRemoval" in multiphysics integrator

**Comment by Dekken** [comment]
https://github.com/PHAREHUB/PHARE/pull/96
